name: MacOS build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '01 01 * * 6'    # Run every Saturday

jobs:

  list-gcc:
    name: list available perl versions
    runs-on: macos-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          print "Version available\n";
          my @versions = perl_versions();
          for my $v (@versions) {
            print "\t$v\n";
          }
          # Don't want anything less then 5.8
          @versions = grep { ! /^5\.6\.*/ } @versions;
          set_output(matrix => {'perl'       => [@versions],
                                'build-bzip2' => [0, 1],
                                'ccflags'    => ['', '-Wc++-compat'],
                                'compiler'   => ['gcc'],
                               },
                    );
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-gcc:
    name: Perl ${{ matrix.perl }} BUILD_BZIP2:${{matrix.build-bzip2}} CC="${{matrix.compiler}}" CCFLAGS:${{matrix.ccflags}}
    runs-on: macos-latest
    needs: list-gcc
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list-gcc.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --quiet --installdeps --notest .
      - name: Build
        run: |
          flags=$( perl -MConfig -e 'print $Config::Config{ccflags}' )
          perl Makefile.PL CCFLAGS="$flags ${{matrix.ccflags}}" CC="${{matrix.compiler}}" && make
        env:
          BUILD_BZIP2: ${{matrix.build-bzip2}}
      - name: Test
        run: make test



  list-gpp:
    name: list available perl versions
    runs-on: macos-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          print "Version available\n";
          my @versions = perl_versions();
          for my $v (@versions) {
            print "\t$v\n";
          }
          # Some failure with older perls + g++
          my $ignore =join "|", qw(
                                    5.18.
                                    5.16.
                                    5.14.
                                    5.12.
                                    5.10.
                                    5.8.
                                    5.6.
          );
          @versions = grep { ! /^$ignore/ } @versions;
          set_output(matrix => {'perl'       => ['latest'],
                                'build-bzip2' => [0, 1],
                                'ccflags'    => ['', '-xc++'],
                                'compiler'   => ['g++'],
                               },
                    );
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-gpp:
    name: Perl ${{ matrix.perl }} BUILD_BZIP2:${{matrix.build-bzip2}} CC="${{matrix.compiler}}" CCFLAGS:${{matrix.ccflags}}
    runs-on: macos-latest
    needs: list-gpp
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list-gpp.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --quiet --installdeps --notest .
      - name: Build
        run: |
          flags=$( perl -MConfig -e 'print $Config::Config{ccflags}' )
          perl Makefile.PL CCFLAGS="$flags ${{matrix.ccflags}}" CC="${{matrix.compiler}}" && make
        env:
          BUILD_BZIP2: ${{matrix.build-bzip2}}
      - name: Test
        run: make test
